const lightTheme = {
  bodyBg: "hsl(0,0%,90%)",
  fontColor: "black",
  fontColorRev: "white",
  accentColor: "#6ecf86",
  accentColorDark: "#20bf6b",
  topNavBg: "white",
  topNavBorder: "hsl(0, 0%, 60%)",
  navIconColor: "black",
  sideNavBg: "white",
  sideNavFontColor: "hsl(0, 0%, 10%)",
  sideNavItemBgHover: "hsl(0, 0%, 80%)",
  sideNavFontColorHover: "hsl(0, 0%, 30%)",
  modalOverlay: "rgba(23, 28, 33,.5)",
  loginModalBg: "black",
  homePageAllTagTagBg: "hsl(0,0%,90%)",
  homePageAllTagTagBorder: "hsl(0,0%,50%)",
  homePageAllTagsTagColor: "hsl(0,0%,30%)",
  homePageChevronColor: "hsl(0,0%,40%)",
  homePageChevronHoveredColor: "hsl(0,0%,10%)",
};
const darkTheme = {
  bodyBg: "hsl(0,0%,10%)",
  fontColor: "white",
  fontColorRev: "black",
  accentColor: "#6ecf86",
  accentColorDark: "#20bf6b",
  topNavBg: "black",
  topNavBorder: "rgb(23, 28, 33)",
  navIconColor: "white",
  sideNavBg: "black",
  sideNavFontColor: "white",
  sideNavItemBgHover: "hsl(0, 0%, 10%)",
  sideNavFontColorHover: "#6ecf86",
  modalOverlay: "rgba(23, 28, 33,.5)",
  loginModalBg: "white",
  homePageAllTagTagBg: "hsl(0,0%,10%)",
  homePageAllTagTagBorder: "hsl(0,0%,50%)",
  homePageAllTagsTagColor: "hsl(0,0%,70%)",
  homePageChevronColor: "hsl(0,0%,60%)",
  homePageChevronHoveredColor: "hsl(0,0%,90%)",
};

export { lightTheme, darkTheme };
